spring.application.name=UberReviewService

server.port = 8081

spring.datasource.url = jdbc:postgresql://localhost:5432/myDB

spring.datasource.username = postgres

spring.datasource.password = root

spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto = update

